spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/trails-manager
    username: postgres
    password: postgres
    hikari:
      data-source-properties: stringtype=unspecified
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false